#!/usr/local/bin/python3

"""

This script was created by Madani Napaul. 

This script gets the files generated by the splitter and sends
each file as a single message to the SQS Queue specified. 

The Lambda function will have a variable for declaring the Bucket Name. 
It will extract the names of the files to check in the Bucket by accessing 
every index until the last index in the JSON array.

"""

import boto3
import json
from os import listdir
from os.path import isfile, join

sqs = boto3.resource("sqs")


queue = sqs.get_queue_by_name(QueueName="cpd-sqs-s1903342")

sqs_split_data = [
    f
    for f in listdir(
        "/Users/madani/Documents/GitHub/cpd_aws_rekognition/enhancement/sqs_data"
    )
    if isfile(
        join(
            "/Users/madani/Documents/GitHub/cpd_aws_rekognition/enhancement/sqs_data", f
        )
    )
]

index = 0

for i in range(0, len(sqs_split_data)):
    last_index = len(sqs_split_data) - 1
    index = 0
    while last_index + 1 != index:
        next_file = sqs_split_data[index]
        with open(
            "/Users/madani/Documents/GitHub/cpd_aws_rekognition/enhancement/sqs_data"
            + next_file
        ) as f:
            data = json.load(f)
            response = queue.send_message(MessageBody=json.dumps(data))
            index = index + 1
    break